#use base image for Docker Hub
FROM node:latest

#set working directory
WORKDIR /app

#copy package.json and package-lock.json files
COPY package*json ./

#install dependencies
RUN npm install

#copy the rest files
COPY . .

#expose the prot the app run
EXPOSE 5173

#start the application
CMD [ "npm" , "run" , "dev" ]